### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by pirica** [tposejank/fnlookup#1]
Using search from Top Nav isnt working 

Error: 404
no cosmetic matching the search parameters was found

https://tposejank.github.io/fnlookup/item.html?q=batman

Nice project!

**Comment by tposejank** [comment]
Hello, I will be providing a solution to this problem, but for now you can use the Search page (Cosmetics -> Search on the navigation bar)

**Comment by pirica** [comment]
Thanks!

**Comment by tposejank** [comment]
This issue has been fixed.
