### ISSUE TITLE
[RQ] Battlepass Preview

### ISSUE THREAD

**Issue by pirica** [tposejank/fnlookup#3]
**What feature do you propose?**
Battlepass Preview

**Screenshots or concepts, if possible**

[Example Link](https://trackernite.com/battlepass/)

![Screenshot_21](https://user-images.githubusercontent.com/11189930/208862253-15d1ce47-c697-43a0-adc5-444a4e1f9c21.png)

**Comment by tposejank** [comment]
This is now added.

**Comment by pirica** [comment]
Would be possible to add a menu to choose previous seasons+chapters?
Many Thanks
