### ISSUE TITLE
[RQ] Add Support to change language for API's

### ISSUE THREAD

**Issue by pirica** [tposejank/fnlookup#4]
**What feature do you propose?**

Ability to change language on backend.js for another language. 

For all Apis:
https://fortnite-api.com/v1/map?language=pt-BR

https://fortniteapi.io/v1/game/augments?lang=pt-br

**Screenshots or concepts, if possible**
![Screenshot_22](https://user-images.githubusercontent.com/11189930/208865009-5425e0c0-e146-4142-a359-a880fc117023.png)

**Comment by tposejank** [comment]
Translation has been added partially. It is still WIP.

**Comment by tposejank** [comment]
This has been added.

**Comment by pirica** [comment]
Would be possible to have a defult lang instead of EN?
Many thanks!
