### ISSUE TITLE
[BUG] Language

### ISSUE THREAD

**Issue by pirica** [tposejank/fnlookup#7]
[BUG] Map - Image its not changing for another languague.
[BUG] Main page - Shop Image its not showing for another languague if is Daily+Featured.

Would be possible to have a _**defult lang instead of EN**_? 

I know its still WIP...

Many thanks!

**Comment by tposejank** [comment]
I will look into it... Thanks for suggesting stuff. A bug where the language of the browser would glitch out was also found by me.

**Comment by pirica** [comment]
No Problem, i send friend request on discord if you would like.
I think on the Main Page - script.js - "if (section === 'Daily')" & Featured
Needs to be translated for all languages hardcore

**Comment by tposejank** [comment]
This bug is fixed.
